stages:
  data_ingestion:
    cmd: python -m src.components.data_ingestion
    deps:
      - src/components/data_ingestion.py
    outs:
      - artifacts/train.csv
      - artifacts/test.csv
      - artifacts/Data.csv
    
  data_transformation:
    cmd: python -m src.components.data_transformation
    deps:
      - src/components/data_transformation.py
      - artifacts/train.csv
      - artifacts/test.csv
    outs:
      - artifacts/preprocessor.pkl
    
  model_trainer:
    cmd: python src/pipeline/train_pipeline.py
    deps:
      - src/components/model_trainer.py
      - src/components/pytorch_model.py
      - artifacts/train.csv
      - artifacts/test.csv
    outs:
      - artifacts/model.pkl
